---
title: "Johnson Creek Ecoregions"
author: "[John Powers](http://sites.uci.edu/powers/)"
date: "`r Sys.Date()`"
output:
  html_document:
    self_contained: no
    lib_dir: libs
    code_folding: hide
    toc: yes
    toc_float: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, message=FALSE}
library(tidyverse)
library(sf)
library(vegan)
library(RColorBrewer)
library(rayshader)
knitr::opts_chunk$set(comment="", cache=T, warning = F, message = F, fig.path = "images-jc/",
                      dev="svglite", dev.args=list(fix_text_size=FALSE),
                      fig.height=3, fig.width=8)
```

# Load GBIF data

```{r load_gbif}
#Portland area
#box <- st_as_sfc("POLYGON((-122.9 45.3,-122 45.3,-122 45.8,-122.9 45.8,-122.9 45.3))") %>% st_set_crs("WGS84")
#Johnson Creek watershed boundary from iNaturalist place
box <- st_read("data/johnsoncreek-inat-154205.kml", quiet=T)
#San Jacinto Mountains research-grade iNaturalist observations
#GBIF.org (19 September 2024) GBIF Occurrence Download  https://doi.org/10.15468/dl.ph88g7
dat.all <- read_tsv("data/0023880-240906103802322.csv.gz")

rare_cutoff <- 100 #drop rare species
dat.common <- dat.all %>% 
  filter(coordinateUncertaintyInMeters < 1000) %>% 
  group_by(species) %>% filter(n()>rare_cutoff) %>% drop_na(species) %>% 
  mutate(species=factor(species), species_int = as.integer(species)) %>% as.data.frame()

dat.points <- dat.common %>% st_as_sf(coords = c("decimalLongitude", "decimalLatitude"), crs = "WGS84") %>% 
  st_intersection(box)
ggplot() + geom_sf(data=box, fill="brown", color="brown") + 
  geom_sf(data=dat.points, aes(color=kingdom), size=0.5) + theme_void() + 
  theme(legend.position = "top", plot.background = element_rect(fill="black"), legend.text=element_text(color="grey")) +
  scale_color_brewer("",palette = "Paired", labels=c(Animalia="animal", Plantae="vegetable", Fungi="fungus"),
                     guide=guide_legend(override.aes = list(size=4)))
```

```{r divide}
group_by_cell <- function(points, grid, min_obs=0) {
  #assign points to cells
  dat.grid.cells <- st_intersects(grid, points) 
  grid$n_obs <- lengths(dat.grid.cells) #count points in each cell
  
  #drop cells with few observations
  cells.full <- which(grid$n_obs > min_obs)
  grid.full <- grid[cells.full,]
  
  #tally number of each species in each cell
  dat.grid <- t(sapply(dat.grid.cells, function(x) table(points$species[x])))
  rownames(dat.grid) <- grid$grid_id
  dat.grid.full <- dat.grid[cells.full,]
  
  list(data = dat.grid.full, grid = grid.full)
}
```

# Draw hexagonal grid

```{r hex}
#make hexagonal grid
hex_dim <- 20 #number of hexagons on each side
hex.sfc <- dat.points %>% st_make_grid(n=c(hex_dim, hex_dim), square = F)
hex <- hex.sfc %>% st_sf() %>% mutate(grid_id = 1:length(lengths(hex.sfc)))

hex.obj <- group_by_cell(dat.points, hex, min_obs=10)
dat.hex <- hex.obj$data
hex.full <- hex.obj$grid
ggplot(hex.full, aes(fill=n_obs)) + geom_sf(linewidth=2) + 
  theme_void() + scale_fill_viridis_c(option="magma", guide="none") + 
  theme(panel.background = element_rect(fill="black"))
```

# Draw Voronoi triangles

```{r voronoi}
#get a sample of points as seeds
n_seeds <- 144
set.seed(1)
dat.sample <- sample_n(dat.points, n_seeds)
tri <- dat.sample %>% st_geometry() %>% do.call(c, .) %>% st_voronoi() %>% 
  st_collection_extract() %>% st_set_crs("WGS84") %>% st_sf() %>%
  mutate(grid_id = 1:nrow(.)) %>%
  st_intersection(box)

tri.obj <- group_by_cell(dat.points, tri, min_obs=10)
dat.tri <- tri.obj$data
tri.full <- tri.obj$grid

ggplot(tri.full, aes(fill=n_obs)) + geom_sf(linewidth=0.5) + 
  theme_void() + scale_fill_viridis_c(option="magma", guide="none") + 
  theme(panel.background = element_rect(fill="black"))
```

# k-Means clustering

```{r kmeans}
#assign clusters with k-means
n_clusters <- 15
pal <- c(brewer.pal(8, "Set2"), brewer.pal(12, "Set3"))[1:n_clusters] %>% set_names(1:n_clusters)

set.seed(1)
hex.km <- dat.hex %>% decostand("hellinger") %>% kmeans(n_clusters)
ggplot(hex.full, aes(fill=factor(hex.km$cluster))) + geom_sf(linewidth=1) + 
  theme_void() + scale_fill_manual(values=pal, guide="none")

set.seed(2)
tri.km <-  dat.tri %>% decostand("hellinger") %>% kmeans(n_clusters)
ggplot(tri.full, aes(fill=factor(tri.km$cluster))) + geom_sf(linewidth=0.5) + 
  theme_void() + scale_fill_manual(values=pal, guide="none")
```

# Arrange clusters in gradient

```{r gradient}
hex.km.nmds <- metaMDS(hex.km$centers, k=1, trace=F)
hex.full$cluster <- factor(hex.km$cluster, levels=order(-t(hex.km.nmds$points)))
ggplot(hex.full, aes(fill=as.integer(cluster))) + geom_sf(linewidth=1) + 
  theme_void() + scale_fill_gradientn(colours = terrain.colors(n_clusters), guide = "none")

tri.km.nmds <- metaMDS(tri.km$centers, k=1, trace=F)
tri.full$cluster <- factor(tri.km$cluster, levels=order(t(tri.km.nmds$points)))
ggplot(tri.full, aes(fill=as.integer(cluster))) + geom_sf(linewidth=0.5) + 
  theme_void() + scale_fill_gradientn(colours = terrain.colors(n_clusters), guide = "none")
```

# NMDS ordination

```{r nmds, fig.height=8, fig.width=8}
plot_nmds <- function(data, grid) {
  nmds <- metaMDS(data, trace=F)
  par(bg="grey40", mar=c(0,0,0,0))
  plot(nmds, type="n", axes=F, ann=F)
  text(nmds, display="species", cex=0.6)
  points(nmds, display="sites", col=terrain.colors(n_clusters)[grid$cluster], pch=19)
  par(bg="white")
}
plot_nmds(dat.hex, hex.full)
plot_nmds(dat.tri, tri.full)
```

